defaults:
  - /../config@_here_ # import default configs
  - _self_

sampler:
  params:
    sampler_type: drhmc
    step_count_factor: 0.9
    step_size_factor: 2
    max_proposals: 3
    reduction_factor: 8
    damping: 1.0
    metric: 1
    adapt_metric: true
    probabilistic: false

wandb:
  tags: "drhmc-baseline"

hydra:
  sweeper: # convert cmd line arguments lists into multiple jobs
    params:
      sampler.chain: range(100)
      sampler.params.step_size_factor: 2
      sampler.params.reduction_factor: 4
      sampler.params.max_proposals: 3