defaults:
  - /../config@_here_ # import default configs
  - _self_

sampler:
  params:
    sampler_type: hmc
    step_count_factor: 0.9
    step_size_factor: null
    step_size: 0.01
    damping: 1.0
    metric: 1
    adapt_metric: false
    probabilistic: false

wandb:
  tags: "hmc-baseline"

hydra:
  # convert cmd line arguments lists into multiple jobs
  sweeper:
    params:
      sampler.chain: range(100)