defaults:
  - overide sampler: drghmc
  - override sampler: drhmc
  - override sampler: nuts
  # - override hydra/launcher: submitit_slurm
  - _self_

sampler:
  generate_history: true 
  generate_metrics: true
  history:
    gradient_budget: 1000000
    burn_in: 0
    chains: 1
    seed: 1234
    thinning: 1
  metric:

posterior:
  dir: posteriors
  name: funnel10

logging:
  logger: wandb
  log_history: true
  log_metrics: true

wandb:
  project: ${posterior.name}
  entity: gilad-turok

hydra:
  mode: MULTIRUN
  verbose: false
  # sweeper:
  #   params:
  #     sampler: drghmc, drhmc, nuts
  # launcher:
  #   tasks_per_node: 128